# Generated by Django 5.2.5 on 2025-08-18 05:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_login_info'),
    ]

    operations = [
        migrations.AddField(
            model_name='login_info',
            name='has_taken_quiz',
            field=models.BooleanField(default=False),
        ),
    ]
