# Generated by Django 5.2.5 on 2025-08-18 05:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_login_info_has_taken_quiz'),
    ]

    operations = [
        migrations.AddField(
            model_name='login_info',
            name='attempts',
            field=models.IntegerField(default=0),
        ),
    ]
